version: "3.9"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./data/db:/data/db
    networks:
      - mysql-compose-network

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

  api:
    image: node:latest
    command: sh -c "npm install && npm start"
    working_dir: /home/node/api
    env_file:
      - .env
    ports:
      - ${API_PORT}:3000
    volumes:
      - ./api:/home/node/api
    networks: 
      - mysql-compose-network
    depends_on:
      - mysql

networks:
  mysql-compose-network:
    driver: bridge
